import type { PricingPlan, Template, BlogPost } from '@/types';

export const DEMO_CREDENTIALS = [
  { role: 'Creator / Influencer', email: 'creator@demo.com', password: 'demo123' },
  { role: 'Brand / Business', email: 'brand@demo.com', password: 'demo123' },
  { role: 'Analyst / Researcher', email: 'analyst@demo.com', password: 'demo123' },
  { role: 'Admin', email: 'admin@demo.com', password: 'demo123' },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 999,
    yearlyPrice: 9990,
    currency: '₹',
    description: 'Perfect for freelancers and solo professionals',
    features: [
      '5 active contracts',
      '3 e-signatures/month',
      'Basic templates library',
      'PDF export',
      'Email notifications',
      '1 GB storage',
      'Standard support',
    ],
    cta: 'Start Free Trial',
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 2999,
    yearlyPrice: 29990,
    currency: '₹',
    description: 'Ideal for growing businesses and teams',
    features: [
      '50 active contracts',
      'Unlimited e-signatures',
      'Full template library',
      'AI contract drafting',
      'Version control & history',
      'Approval workflows',
      'Advanced analytics',
      '50 GB storage',
      'Priority support',
    ],
    popular: true,
    cta: 'Start Free Trial',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 7999,
    yearlyPrice: 79990,
    currency: '₹',
    description: 'For large organizations with complex needs',
    features: [
      'Unlimited contracts',
      'Unlimited e-signatures',
      'Custom template builder',
      'Advanced AI features',
      'Risk detection & compliance',
      'Multi-level approvals',
      'CRM integration',
      'Custom workflows',
      'Unlimited storage',
      'Dedicated account manager',
      'SLA guarantee',
      'Custom branding',
    ],
    cta: 'Contact Sales',
  },
];

export const CONTRACT_TEMPLATES: Template[] = [
  {
    id: 'nda-standard',
    name: 'Non-Disclosure Agreement (NDA)',
    category: 'Legal',
    description: 'Standard bilateral NDA for business relationships and partnerships.',
    clauses: 12,
    usageCount: 4821,
    tags: ['NDA', 'Confidentiality', 'Legal'],
    preview: 'This Non-Disclosure Agreement...',
  },
  {
    id: 'employment-offer',
    name: 'Employment Offer Letter',
    category: 'HR',
    description: 'Comprehensive employment offer letter with compensation and benefits.',
    clauses: 18,
    usageCount: 3241,
    tags: ['Employment', 'HR', 'Offer'],
    preview: 'We are pleased to offer you...',
  },
  {
    id: 'service-agreement',
    name: 'Service Agreement',
    category: 'Business',
    description: 'Professional service agreement for contractors and freelancers.',
    clauses: 15,
    usageCount: 6102,
    tags: ['Service', 'Contractor', 'Business'],
    preview: 'This Service Agreement is entered...',
  },
  {
    id: 'influencer-brand',
    name: 'Influencer Brand Deal',
    category: 'Marketing',
    description: 'Complete influencer marketing agreement with deliverables and compensation.',
    clauses: 14,
    usageCount: 2389,
    tags: ['Influencer', 'Brand', 'Marketing'],
    preview: 'This Influencer Agreement...',
  },
  {
    id: 'saas-subscription',
    name: 'SaaS Subscription Agreement',
    category: 'Technology',
    description: 'Software-as-a-Service subscription terms and conditions.',
    clauses: 22,
    usageCount: 1847,
    tags: ['SaaS', 'Technology', 'Subscription'],
    preview: 'These Terms govern your use...',
  },
  {
    id: 'partnership-agreement',
    name: 'Business Partnership Agreement',
    category: 'Business',
    description: 'Joint venture and partnership agreement with profit sharing clauses.',
    clauses: 20,
    usageCount: 1593,
    tags: ['Partnership', 'Joint Venture', 'Business'],
    preview: 'This Partnership Agreement...',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Future of AI-Powered Contract Management in 2025',
    excerpt: 'How artificial intelligence is revolutionizing the way businesses create, manage, and analyze contracts.',
    content: '',
    author: 'Priya Sharma',
    authorRole: 'Legal Technology Expert',
    category: 'AI & Technology',
    tags: ['AI', 'Contract Management', 'Future'],
    publishedAt: '2025-03-15',
    readTime: 7,
    coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    featured: true,
  },
  {
    id: '2',
    title: 'Top 10 Contract Clauses Every Business Must Include',
    excerpt: 'Essential contract clauses that protect your business interests and minimize legal risk.',
    content: '',
    author: 'Rahul Verma',
    authorRole: 'Corporate Legal Counsel',
    category: 'Legal Tips',
    tags: ['Clauses', 'Business', 'Legal'],
    publishedAt: '2025-03-10',
    readTime: 5,
    coverImage: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&q=80',
    featured: false,
  },
  {
    id: '3',
    title: 'E-Signature Compliance: What You Need to Know in India',
    excerpt: 'A comprehensive guide to legally valid electronic signatures under the IT Act 2000.',
    content: '',
    author: 'Ananya Nair',
    authorRole: 'Compliance Specialist',
    category: 'Compliance',
    tags: ['E-Signature', 'India', 'Legal'],
    publishedAt: '2025-03-05',
    readTime: 6,
    coverImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    featured: false,
  },
  {
    id: '4',
    title: 'Reducing Contract Cycle Time by 80% with Automation',
    excerpt: 'Real-world case study on how automation transforms contract workflows and accelerates deal closures.',
    content: '',
    author: 'Vikram Patel',
    authorRole: 'Operations Director',
    category: 'Case Study',
    tags: ['Automation', 'Efficiency', 'Workflow'],
    publishedAt: '2025-02-28',
    readTime: 8,
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    featured: false,
  },
  {
    id: '5',
    title: 'Influencer Contracts: Protecting Both Sides of the Deal',
    excerpt: 'Key provisions every influencer marketing agreement should include for brand and creator protection.',
    content: '',
    author: 'Meera Kapoor',
    authorRole: 'Marketing Law Expert',
    category: 'Marketing',
    tags: ['Influencer', 'Brand Deal', 'Creator'],
    publishedAt: '2025-02-20',
    readTime: 5,
    coverImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80',
    featured: false,
  },
  {
    id: '6',
    title: 'Risk Detection: Using AI to Flag Contract Vulnerabilities',
    excerpt: 'How machine learning models identify risky clauses and protect businesses from unfavorable terms.',
    content: '',
    author: 'Arjun Mehta',
    authorRole: 'AI Research Lead',
    category: 'AI & Technology',
    tags: ['Risk', 'AI', 'Contract Analysis'],
    publishedAt: '2025-02-15',
    readTime: 9,
    coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    featured: false,
  },
];

export const NAV_LINKS = [
  { label: 'Home', path: '/' },
  { label: 'Features', path: '/features' },
  { label: 'Pricing', path: '/pricing' },
  { label: 'Blog', path: '/blog' },
  { label: 'About', path: '/about' },
  { label: 'Contact', path: '/contact' },
];

export const FEATURE_LIST = [
  {
    icon: 'FileText',
    title: 'Smart Contract Creation',
    description: 'Create contracts in minutes using AI-powered templates and a smart clause library with dynamic placeholders.',
    color: 'from-purple-500 to-violet-600',
  },
  {
    icon: 'PenTool',
    title: 'E-Signature System',
    description: 'Multi-party digital signing with sequential and parallel workflows. Legally binding and IT Act compliant.',
    color: 'from-pink-500 to-rose-600',
  },
  {
    icon: 'GitBranch',
    title: 'Version Control',
    description: 'Full change history, side-by-side comparison, and one-click rollback for every contract version.',
    color: 'from-blue-500 to-cyan-600',
  },
  {
    icon: 'Brain',
    title: 'AI Contract Intelligence',
    description: 'AI-powered drafting, clause recommendations, risk detection, and contract analysis at your fingertips.',
    color: 'from-amber-500 to-orange-600',
  },
  {
    icon: 'Workflow',
    title: 'Approval Automation',
    description: 'Multi-level conditional approval workflows that route contracts automatically to the right stakeholders.',
    color: 'from-green-500 to-emerald-600',
  },
  {
    icon: 'Shield',
    title: 'Security & Compliance',
    description: 'Bank-grade encryption, audit trails, compliance checklists, and complete regulatory documentation.',
    color: 'from-red-500 to-rose-600',
  },
  {
    icon: 'BarChart3',
    title: 'Analytics Dashboard',
    description: 'Real-time insights on contract status, expiry risks, approval timelines, and portfolio value.',
    color: 'from-teal-500 to-cyan-600',
  },
  {
    icon: 'Search',
    title: 'Smart Repository',
    description: 'Centralized contract storage with full-text search, tagging, categorization, and advanced filters.',
    color: 'from-indigo-500 to-purple-600',
  },
  {
    icon: 'Bell',
    title: 'Smart Notifications',
    description: 'Proactive alerts for expiry, renewal, pending actions, and critical contract milestones.',
    color: 'from-yellow-500 to-amber-600',
  },
];
